# Generated by Django 6.0.3 on 2026-04-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='studentcurse', to='course.curse'),
            preserve_default=False,
        ),
    ]
