# Generated by Django 6.0.3 on 2026-04-01 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CS', 'Ciência da Computação'), ('ENGC', 'Engenharia Civil'), ('MED', 'Medicina'), ('DIR', 'Direito'), ('ADM', 'Administração'), ('ECO', 'Economia'), ('PSQ', 'Psicologia'), ('ENF', 'Enfermagem'), ('ARQ', 'Arquitetura'), ('PED', 'Pedagogia')])),
                ('curse_code', models.CharField(max_length=6)),
                ('semesters', models.IntegerField(validators=[django.core.validators.MinValueValidator(8, 'A duração mínima dos cursos são 8 semestres '), django.core.validators.MaxValueValidator(12, 'A duração máxima dos cursos são 12 semestres')])),
            ],
        ),
    ]
